### PR TITLE
Improved 1Ficihier URL Validation

### LINKED ISSUE #2: [debrid.sh] Properly validate URLs

### PR DESCRIPTION
**Pull request by h4ckitt**
Added Proper Validation Of The 1fichier URL

This PR Closes #2

### CODE REVIEW

**Comment by manuGMG** [comment]
This looks great so far, however, it's missing the rest of the 1Fichier domains as shown below.
```
domains = [
    '1fichier.com/',
    'afterupload.com/',
    'cjoint.net/',
    'desfichiers.com/',
    'megadl.fr/',
    'mesfichiers.org/',
    'piecejointe.net/',
    'pjointe.com/',
    'tenvoi.com/',
    'dl4free.com/'
]
```

**Comment by h4ckitt** [comment]
Ohh, I Didn't Know That.

I'll Add Them And Commit.

Thanks For The Great Work Though.

**Comment by manuGMG** [comment]
Perfect, thanks for your contribution!

**Comment by h4ckitt** [comment]
Thanks Boss.

I'm Sorry For Messing Up The Comments, Didn't Realize.

Bad Coding Practice On My Part :facepalm:

**Pull request merged**
